### ISSUE TITLE
與環保署水質監測資料承辦人建立有效溝通

### ISSUE THREAD

**Issue by yuukumo** [TaiBON/biodiv_indicators#17]
## 目的
* 釐清現有資料中待議問題的處理方式
* 產生 TaiBON 團隊和環保署都能接受的資料版本，並發布至政府開放平台

## 任務清單
- [ ] 確認當前的承辦人是誰
- [ ] 與承辦人約時間
- [ ] 進行討論會
- [ ] 會議紀錄整理與發布
- [ ] 確認資料是否已順利發布至政府開放平台

**Comment by melissa0520** [comment]
已與承辦人郭權展技正約10/3下午前往環管處訪談
